const KEYCODE = {
    KEYCODE_LEFT: 37,
    KEYCODE_UP: 38,
    KEYCODE_RIGHT: 39,
    KEYCODE_DOWN: 40,
    KEYCODE_DELETE: 46,
    KEYCODE_BACKSPACE: 8,
    KEYCODE_ESC: 27,
    KEYCODE_C: 67,
    KEYCODE_V: 86
};

export default KEYCODE;